# Generated by Django 4.2.6 on 2023-12-02 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_alter_processors_options_motherboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('productcode', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('prodsupplier', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='manufacturer',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.manufacturer'),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='manufacturer',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.manufacturer'),
        ),
        migrations.AlterField(
            model_name='processors',
            name='manufacturer',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.manufacturer'),
        ),
    ]
