# Generated by Django 4.2.6 on 2023-12-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_graphicscard_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.RemoveField(
            model_name='graphicscard',
            name='prodsupplier',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='prodsupplier',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='prodsupplier',
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='supplier',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.supplier'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='supplier',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.supplier'),
        ),
        migrations.AddField(
            model_name='processors',
            name='supplier',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.supplier'),
        ),
    ]
