# Generated by Django 4.2.6 on 2023-12-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_supplier_remove_graphicscard_prodsupplier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
    ]
