# Generated by Django 4.2.6 on 2024-01-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_ram_powersupply'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'rammanufacturers',
            },
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name_plural': 'manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='powersupply',
            options={'verbose_name_plural': 'Power Supplies'},
        ),
        migrations.AlterModelOptions(
            name='processor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'suppliers'},
        ),
        migrations.RemoveField(
            model_name='ram',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='ram',
            name='rammanufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.rammanufacturer'),
        ),
    ]
